-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 13:57:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assetdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `assetdb` ;

-- -----------------------------------------------------
-- Schema assetdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assetdb` DEFAULT CHARACTER SET utf8 ;
USE `assetdb` ;

-- -----------------------------------------------------
-- Table `assetdb`.`AUTH_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assetdb`.`AUTH_USER` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`AUTH_USER` 
(
  `username` VARCHAR(60) NOT NULL PRIMARY KEY,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(80) NULL,
  `fullname` VARCHAR(120) NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE = InnoDB;

/* Add Comments */
ALTER TABLE auth_user COMMENT = 'Usuario para autenticación';

-- -----------------------------------------------------
-- Table `assetdb`.`AUTH_USER_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assetdb`.`AUTH_USER_ROLE` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`AUTH_USER_ROLE` 
(
  `id` INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `role` VARCHAR(60) NOT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  INDEX `fk_AUTH_USER_ROLE_AUTH_USER_idx` (`username` ASC),
  CONSTRAINT `fk_AUTH_USER_ROLE_AUTH_USER`
    FOREIGN KEY (`username`)
    REFERENCES `assetdb`.`AUTH_USER` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

/* Add Comments */
ALTER TABLE auth_user_role COMMENT = 'Rol para autorización de usuarios';

/************ Update: Tables ***************/

/******************** Add Table: area ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`area` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`area`
(
  asset_owner_id INTEGER NOT NULL,
  city_id INTEGER NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Primary Key */
ALTER TABLE area ADD CONSTRAINT pkarea
  PRIMARY KEY (asset_owner_id);

/* Add Comments */
ALTER TABLE area COMMENT = 'Area propietaria del activo fijo';

/* Add Indexes */
CREATE UNIQUE INDEX area_city_id_Idx ON area (city_id);


/******************** Add Table: asset_owner ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`asset_owner` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`asset_owner`
(
  asset_owner_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  asset_name VARCHAR(150) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Comments */
ALTER TABLE asset_owner COMMENT = 'Propietario del activo fijo (area o persona)';


/******************** Add Table: asset_status ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`asset_status` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`asset_status`
(
  asset_status_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Comments */
ALTER TABLE asset_status COMMENT = 'Tabla con estados del activo fijo';


/******************** Add Table: asset_type ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`asset_type` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`asset_type`
(
  asset_type_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(100) NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Comments */
ALTER TABLE asset_type COMMENT = 'Tipo de activo';


/******************** Add Table: city ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`city` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`city`
(
  city_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  city_code VARCHAR(10),
  name VARCHAR(150) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB;

/* Add Comments */
ALTER TABLE city COMMENT = 'Ciudad a la que pertenece el área';


/******************** Add Table: fixed_asset ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`fixed_asset` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`fixed_asset`
(
  fixed_asset_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  asset_owner_id INTEGER NOT NULL,
  asset_status_id INTEGER NOT NULL,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(500) NULL,
  asset_type_id INTEGER NOT NULL,
  `serial` VARCHAR(100) NOT NULL,
  inventory_num VARCHAR(100) NOT NULL,
  weight DECIMAL(10, 2) NULL,
  high DECIMAL(10, 2) NULL,
  width DECIMAL(10, 2) NULL,
  long_value DECIMAL(10, 2) NULL,
  purchase_value DECIMAL(20, 2) NULL,
  purchase_date DATE NULL,
  withdrawal_date DATE NULL,
  color VARCHAR(70) NULL,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Comments */
ALTER TABLE fixed_asset COMMENT = 'Tabla de activos fijos';


/******************** Add Table: person ************************/

/* Build Table Structure */
DROP TABLE IF EXISTS `assetdb`.`person` ;
CREATE TABLE IF NOT EXISTS `assetdb`.`person`
(
  asset_owner_id INTEGER NOT NULL,
  document_num VARCHAR(30) NULL,
  phone VARCHAR(20) NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  created_by_user VARCHAR(70) NOT NULL,
  updated_by_user VARCHAR(70) NULL
) ENGINE=InnoDB;

/* Add Primary Key */
ALTER TABLE person ADD CONSTRAINT pkperson
  PRIMARY KEY (asset_owner_id);

/* Add Comments */
ALTER TABLE person COMMENT = 'Persona propietaria del activo fijo';


/************ Add Foreign Keys ***************/

/* Add Foreign Key: city_area_fk */
ALTER TABLE area ADD CONSTRAINT city_area_fk
  FOREIGN KEY (city_id) REFERENCES city (city_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_area_asset_owner */
ALTER TABLE area ADD CONSTRAINT fk_area_asset_owner
  FOREIGN KEY (asset_owner_id) REFERENCES asset_owner (asset_owner_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_fixed_asset_asset_owner */
ALTER TABLE fixed_asset ADD CONSTRAINT fk_fixed_asset_asset_owner
  FOREIGN KEY (asset_owner_id) REFERENCES asset_owner (asset_owner_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_fixed_asset_asset_status */
ALTER TABLE fixed_asset ADD CONSTRAINT fk_fixed_asset_asset_status
  FOREIGN KEY (asset_status_id) REFERENCES asset_status (asset_status_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_fixed_asset_asset_type */
ALTER TABLE fixed_asset ADD CONSTRAINT fk_fixed_asset_asset_type
  FOREIGN KEY (asset_type_id) REFERENCES asset_type (asset_type_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_person_asset_owner */
ALTER TABLE person ADD CONSTRAINT fk_person_asset_owner
  FOREIGN KEY (asset_owner_id) REFERENCES asset_owner (asset_owner_id)
  ON UPDATE NO ACTION ON DELETE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/* Initialize auth_user */
INSERT INTO auth_user (username,password,email,fullname,enabled)
VALUES ('alejo','yb6x2g32vzm1gt0b','alejocadena@ejemplo.com','Alejandro Cadena',1);

/* Initialize auth_user_role */
INSERT INTO auth_user_role (username,role)
VALUES ('alejo','USER');

/* Initialize asset_status */
INSERT INTO asset_status (name,created_by_user)
VALUES 
  ('Activo','alejo'),
  ('Dado de baja','alejo'),
  ('En reparación','alejo'),
  ('Disponible','alejo'),
  ('Asignado','alejo');

/* Initialize asset_status */
INSERT INTO asset_status (name,created_by_user)
VALUES 
  ('Activo','alejo'),
  ('Dado de baja','alejo'),
  ('En reparación','alejo'),
  ('Disponible','alejo'),
  ('Asignado','alejo');

/* Initialize asset_type */
INSERT INTO asset_type (name,created_by_user)
VALUES 
  ('Tangible','alejo'),
  ('Intangible','alejo');

/* Initialize asset_type */
INSERT INTO asset_owner (asset_name,created_by_user)
VALUES 
('Juan David','alejo'),
('Área logística','alejo');

/* Initialize cities */
INSERT INTO city (city_code,name)
VALUES 
    ('11001000','BOGOTA, D.C.'),
    ('05001000','MEDELLIN'),
    ('66001000','PEREIRA'),
    ('76001000','CALI'),
    ('54001000','CUCUTA'),
    ('68001000','BUCARAMANGA'),
    ('08001000','BARRANQUILLA'),
    ('17001000','MANIZALES'),
    ('73001000','IBAGUE'),
    ('13001000','CARTAGENA');

/* Initialize person */
INSERT INTO person (asset_owner_id,document_num,phone,created_by_user)
VALUES 
(1,'1022372356','3016598028','alejo');

/* Initialize area */
INSERT INTO area (asset_owner_id,city_id,created_by_user)
VALUES 
(2,1,'alejo');

/* Initialize fixed_asset */
INSERT INTO fixed_asset (
  asset_owner_id,
  asset_status_id,
  name,
  description,
  asset_type_id,
  `serial`,
  inventory_num,
  weight,
  high,
  width,
  long_value,
  purchase_value,
  purchase_date,
  withdrawal_date,
  color,
  created_by_user
) VALUES (
  1,
  1,
  'Computador portátil',
  'Lenovo',
  1,
  '1001648732',
  1,
  2.5,
  18,
  1.8,
  25,
  1800000,
  CURRENT_TIMESTAMP,
  NULL,
  'negro',
  'alejo'
),
(
  2,
  1,
  'Mesa',
  'Mesa de estudio',
  1,
  '5847564',
  8,
  12,
  1.1,
  2,
  2,
  35000000,
  CURRENT_TIMESTAMP,
  NULL,
  'Café',
  'alejo'
);



